name: Build HUP Generator
run-name: Building HUP Generator Windows executable

on:
  push:
    tags:
      - 'v*'  # Run on version tags
  workflow_dispatch:  # Enable manual triggering
    inputs:
      create_release:
        description: 'Create a new release'
        required: false
        default: false
        type: boolean

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Install dependencies
        run: |
          echo "Installing Python dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Ensure HUP directory exists
        run: |
          echo "Checking and creating HUP directory if needed..."
          if (!(Test-Path -Path "HUP")) {
            New-Item -Path "HUP" -ItemType Directory
          }
          echo "Creating placeholder template file for build..."
          Set-Content -Path "HUP\origineel (niet aanpassen).xlsx" -Value "This is a placeholder"
          
      - name: Build Windows executable
        run: |
          echo "Building Windows executable..."
          python build_app.py
          echo "Build completed"
        
      - name: List generated files
        run: |
          echo "Files in dist directory:"
          dir dist
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HUP_Generator_Windows
          path: dist/*.exe
          compression-level: 0  # No compression for binary files
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.create_release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
          draft: true
          name: HUP Generator ${{ github.ref_name || format('Build-{0}', github.run_number) }}
          body: |
            HUP Generator ${{ startsWith(github.ref, 'refs/tags/') && format('version {0}', github.ref_name) || format('build #{0}', github.run_number) }}
            
            Windows executable built automatically.
            
            ## Installation
            Download the .exe file and run it directly.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
