name: Build Executables

on:
  push:
    tags:
      - 'v*'  # Run on version tags

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: 3.9
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Ensure HUP directory exists
        run: |
          mkdir -p HUP
          echo "Creating placeholder template file for build"
          echo "This is a placeholder" > "HUP/origineel (niet aanpassen).xlsx"
          
      - name: Build Windows executable
        run: python build_app.py
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: HUP_Generator_Windows
          path: dist/*.exe
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
          draft: true
          name: HUP Generator ${{ github.ref_name }}
          body: |
            HUP Generator version ${{ github.ref_name }}
            
            Windows executable built automatically.
            
            ## Installation
            Download the .exe file and run it directly.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
